name: CI
on:
  push:
    branches:
      - '**'

# TODO: make a version that runs on pull_request

env:
  RUST_LIB_BACKTRACE: 1
  RAYON_NUM_THREADS: 1

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master 

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install graco
      run: |
        npm install -g pnpm spellchecker
        npm install -g graco
        echo "NODE_PATH=$(npm config get prefix)/lib/node_modules:$NODE_PATH" >> $GITHUB_ENV
        echo "NODE_LOG=debug" >> $GITHUB_ENV
    
    - name: Update rustup
      run: rustup self update

    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install 1.62 -c rust-docs
        rustup default 1.62

    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.27/mdbook-v0.4.27-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        curl -sSL https://github.com/cognitive-engineering-lab/mdbook-quiz/releases/download/v0.2.13/mdbook-quiz-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> ${GITHUB_PATH}

    - name: Report versions
      run: |
        rustup --version
        rustc -Vv
        mdbook --version

    - name: Install js-extensions
      run: |
        cd js-extensions
        pnpm commit-check

    - name: Run mdbook tests
      run: mdbook test

    - name: Deploy to Github Pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
        cname: rust-book.cs.brown.edu
